export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Prizes } from './Prizes'
export { default as Raffles } from './Raffles'
export { default as Report } from './Report'
export { default as Settings } from './Settings'
 export { default as Winners } from './Winners'
